---
title: "Welcome to my website"
description: |
  how I created this site using Distill
date: 10-14-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

Welcome to my personal website! It was made with [Distill](https://rstudio.github.io/distill/), an R package that creates simple blogs and websites. I plan to use this blog to share my research and writings, primarily related to housing.

This is my third attempt at creating a personal website within a year, which is a lot, but to be fair I had no idea what I was doing. After a year of trial and error I'm finally beginning to understand the basics of web development and the limitations of my abilities.

Last fall I created a blog using [Ghost](https://ghost.org/), a free and open source content management system (CMS) that makes blogging easy and pretty. [For \$5 a month](https://ghost.org/docs/install/digitalocean/) you can get a site up and running in an instant. Since the CMS is accessed online, it's easy to draft posts on any device, including mobile. This first website was a daily blog meant to help me overcome an aversion to writing. It helped me build a writing habit and I made steady progress on housing-related research, at least for a while. But Ghost ultimately is not the best option if you're analyzing and writing about data. I knew I wanted to use R to create and share tables, graphs, and maps.

<aside>

I also came to regret the idea of a daily blog and shut it down after five months. It's one thing to write daily, it's another to share something with others every day. It held me accountable to a schedule, but my writing quality suffered because I didn't have the time I needed to step away, edit, and refine.

</aside>

Over the summer I wrote the capstone for my master's degree. Not only was the paper overly broad and disjointed, but a month before it was due I decided to switch from writing it in Word to creating a [bookdown](https://bookdown.org/yihui/bookdown/) website, something I'd never done before. I learned a hard lesson to not use a new program so close to a deadline.[^1] In hindsight, I could have still used R for data analysis and manipulation, but I spent too much time trying to learn how to use bookdown and the quality of my paper suffered.

[^1]: This is actually like the third time I've learned this lesson.

I always planned to continue my research after graduation, the question was how. Despite repeated attempts to revise my capstone, I think the best approach is to split it up into smaller chunks. My personal website had also been down since May, so I wanted to get that back up and running.

Just under a month ago I created my first [blogdown](https://bookdown.org/yihui/blogdown/) website. It felt like the logical step after using bookdown. I got the website online but I felt in over my head. There were a lot of new files I didn't understand and the default template felt overwhelming. Originally I was going to push through; I at least knew how to make a new post. But once I started writing I found citations were not natively working.

While searching for how to use citations, I learned about Distill and realized this is the program I probably should have been using all along. I don't have to worry about themes or keeping it updated. There's fewer options, so I'm not overwhelmed, and the R stuff seems to manage better. Citations work right out of the gate. I can focus on the writing and analysis rather than trying to figure out how to make the website work.

Maybe one day I'll outgrow Distill, but I have a lot to learn before that happens.
