---
title: "Code Enforcement Data"
description: |
  A short description of the post.
author:
  - name: Sarah Johnson
date: 2021-11-09
output:
  distill::distill_article:
    self_contained: false
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

| Reported Date           | Number of Requests |
|-------------------------|--------------------|
| 2016                    | 30,361             |
| 2017                    | 26,196             |
| 2018                    | 26,846             |
| 2019                    | 27,558             |
| 2020                    | 26,194             |
| 2021 (as of 11/09/2021) | 27,326             |

: Code Enforcement requests by reported date.

Below are cases that have not been marked "Closed" or "Resolved."

| Year | Active Cases |
|------|--------------|
| 2016 | 131          |
| 2017 | 105          |
| 2018 | 495          |
| 2019 | 872          |
| 2020 | 825          |
| 2021 | 5,572        |

: Active cases for each year.

AHHH

```{r}
CE2 <- CE %>% filter(str_detect(REQUEST_TYPE, "Derelict|Miscellaneous"))
noNA <- CE2 %>% filter(!is.na(RESOLUTION_SUMMARY))
```

```{r}
yard <- c("CVOYC", "VOYC")
yardM <- str_c(yard, collapse = "|")
```

```{r}
CE3 <- noNA %>% filter(!str_detect(RESOLUTION_CODE, yardM))
```

```{r}
CE3 %>% count(RESOLUTION_CODE) %>% arrange(desc(n))
```

```{r}
CVOM <- CE3 %>% 
  filter(RESOLUTION_CODE == "CVOM") %>% 
  select(-c(RESOLUTION_CODE, RESOLUTION_CODE_MEANING))
```

```{r}
CVOM %>% count(RESOLUTION_SUMMARY) %>% arrange(desc(n))
```

```{r}
cvomw <- c("comp. v.o. - miscellaneous", "cvom")

compliance <- c("in compliance", "resolved", "at the time of inspection the violation has been corrected", "violation has been corrected", "repairs made", "repaired", "incompliance at the time of recheck", "repairs made in compliance", "corrected", "in compliance at the time of recheck")
compM <- str_c(compliance, collapse = "|")

perInspect <- c("per inspector")
```

```{r}
CVOM %>% filter(str_detect(RESOLUTION_SUMMARY, compM))
```
