---
title: "Population and Housing"
description: |
  Census data for Memphis, Shelby County, and the Memphis MSA.
author:
  - name: Sarah Johnson
date: 2022-06-20
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(gt)
```

```{r include=FALSE}
yrs <- c(2010, 2020)
```

```{r eval=FALSE, include=FALSE}
v20 <- load_variables(2020, "acs5")

hsgMphs <- map_dfr(yrs, ~ {
  get_acs(
    geography = "place",
    state = "TN",
    table = "B25002",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year") %>%
  filter(str_detect(NAME, "Memphis"))

hsgSh <- map_dfr(yrs, ~ {
  get_acs(
    geography = "county",
    state = "TN",
    county = "Shelby",
    table = "B25002",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year")

hsgMSA <- map_dfr(yrs, ~ {
  get_acs(
    geography = "cbsa",
    table = "B25002",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year") %>%
  filter(str_detect(NAME, "Memphis"))
```

```{r include=FALSE}
avghsgMphs <- map_dfr(yrs, ~ {
  get_acs(
    geography = "place",
    state = "TN",
    table = "B25010",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year") %>%
  filter(str_detect(NAME, "Memphis"))

avghsgSh <- map_dfr(yrs, ~ {
  get_acs(
    geography = "county",
    state = "TN",
    county = "Shelby",
    table = "B25010",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year")

avghsgMSA <- map_dfr(yrs, ~ {
  get_acs(
    geography = "cbsa",
    table = "B25010",
    year = .x,
    cache_table = TRUE
  )
}, .id = "year") %>%
  filter(str_detect(NAME, "Memphis"))
```

```{r eval=FALSE, include=FALSE}
hsg <- rbind(hsgMphs, hsgSh, hsgMSA) %>% 
  mutate(year = recode(year, '1' = 2010, '2' = 2020),
         variable = recode(variable,
                           'B25002_001' = 'Total Housing Units',
                           'B25002_002' = 'Occupied Units',
                           'B25002_003' = 'Vacant Units'))
```

```{r include=FALSE}
avghsg <- rbind(avghsgMphs, avghsgSh, avghsgMSA) %>% 
  mutate(year = recode(year, '1' = 2010, '2' = 2020),
         variable = recode(variable,
                           'B25010_001' = 'Avg HH Size',
                           'B25010_002' = 'Owner Occupied',
                           'B25010_003' = 'Renter Occupied'))
```

```{r eval=FALSE, include=FALSE}
popMphs <- map_dfr(yrs, ~ {
  get_acs(geography = "place",
                state = "TN",
                variables = "B25008_001",
                year = .x,
                cache_table = TRUE)
}, .id = "year") %>% 
  filter(str_detect(NAME, "Memphis")) 

popSh <- map_dfr(yrs, ~ {
  get_acs(geography = "county",
                state = "TN", county = "Shelby",
                variables = "B25008_001",
                year = .x,
                cache_table = TRUE)
}, .id = "year")

popMSA <- map_dfr(yrs, ~ {
  get_acs(geography = "cbsa",
                variables = "B25008_001",
                year = .x,
                cache_table = TRUE)
}, .id = "year") %>% 
  filter(str_detect(NAME, "Memphis"))
```

```{r eval=FALSE, include=FALSE}
pop <- rbind(popMphs, popSh, popMSA) %>% 
  mutate(year = recode(year, '1' = 2010, '2' = 2020),
         variable = recode(variable,
                           'B25008_001' = 'Pop in Housing Units'))
```

```{r eval=FALSE, include=FALSE}
pophsg <- rbind(pop, hsg) %>% 
  mutate(NAME = recode(NAME, 
                       'Memphis city, Tennessee' = 'Memphis',
                       'Shelby County, Tennessee' = 'County',
                       'Memphis, TN-MS-AR Metro Area' = 'Metro'))

pophsg$NAME <- factor(pophsg$NAME, levels = c('Memphis', 'County', 'Metro'))
```

```{r eval=FALSE, include=FALSE}
write_csv(pophsg, "../_data/pophsg.csv")
```

```{r}
pophsg <- read_csv("../_data/pophsg.csv")
```

```{r}
pophsgIn <- rbind(pophsg, avghsg) %>% 
  group_by(NAME, variable) %>% 
  mutate(pct_chg = (estimate/lag(estimate) - 1)) %>% 
  filter(!is.na(pct_chg)) %>% 
  select(-c(year, GEOID, moe)) %>% ungroup() 
```

```{r}
pophsgEx <- pophsg %>% 
  select(-c(GEOID, moe)) %>% 
  pivot_wider(names_from = NAME, values_from = estimate) %>% 
  mutate(Metro = Metro - County,
         County = County - Memphis) %>% 
  pivot_longer(cols = c(Memphis, County, Metro), 
               names_to = "NAME", 
               values_to = "estimate") %>% 
  group_by(NAME, variable) %>% 
  mutate(pct_chg = (estimate/lag(estimate) - 1)) %>% 
  filter(!is.na(pct_chg)) %>% 
  select(-year) %>% 
  ungroup()
```

```{r}
totalIn <- pophsgIn %>% 
  filter(variable == "Pop in Housing Units" | 
           variable == "Occupied Units") %>% 
  mutate(variable = recode(variable, 
         'Pop in Housing Units' = 'Population',
         'Occupied Units' = 'Households'))

hsgtblIn <- pophsgIn %>% 
  filter(str_detect(variable, "Units") & !str_detect(variable, "Pop"))

totalEx <- pophsgEx %>% 
  filter(variable == "Pop in Housing Units" | 
           variable == "Occupied Units") %>% 
  mutate(variable = recode(variable, 
         'Pop in Housing Units' = 'Population',
         'Occupied Units' = 'Households'))

hsgtblEx <- pophsgEx %>% 
  filter(str_detect(variable, "Units") & !str_detect(variable, "Pop"))
```

```{r layout='l-page'}
totalIn %>% 
  pivot_wider(names_from = NAME, 
              values_from = c(estimate, pct_chg)) %>% 
  gt() %>% 
  tab_spanner(
    label = "Memphis",
    columns = c(estimate_Memphis, pct_chg_Memphis)
  ) %>% 
  tab_spanner(
    label = "Shelby County",
    columns = c('estimate_County', 'pct_chg_County')
  ) %>% 
  tab_spanner(
    label = "Memphis Metro",
    columns = c('estimate_Metro', 'pct_chg_Metro')
  ) %>% 
  fmt_percent(columns = c(
    'pct_chg_Memphis',
    'pct_chg_County',
    'pct_chg_Metro'
    )) %>% 
  fmt_number(columns = c(
    'estimate_Memphis', 
    'estimate_County',
    'estimate_Metro'),
    decimals = 0) %>% 
  cols_label(
    'estimate_Memphis' = '2020',
    'pct_chg_Memphis' = '2010-2020',
    'estimate_County' = '2020', 
    'pct_chg_County' = '2010-2020',
    'estimate_Metro' = '2020', 
    'pct_chg_Metro' = '2010-2020',
    'variable' = ' '
  ) %>% 
  tab_footnote(
    footnote = "Population is the Total Population in Occupied Housing, which excludes people living in group quarters."
  ) %>% 
  tab_footnote(
    footnote = "Source: 5-Year ACS 2005-2010 & 2015-2020"
  ) %>% 
  tab_header(
    title = "Population and Households in Memphis Area",
    subtitle = "Inclusive geographies"
  )
```

```{r layout='l-page'}
totalEx %>% 
  pivot_wider(names_from = NAME, 
              values_from = c(estimate, pct_chg)) %>% 
  gt() %>% 
  tab_spanner(
    label = "Memphis",
    columns = c(estimate_Memphis, pct_chg_Memphis)
  ) %>% 
  tab_spanner(
    label = "Shelby County",
    columns = c('estimate_County', 'pct_chg_County')
  ) %>% 
  tab_spanner(
    label = "Memphis Metro",
    columns = c('estimate_Metro', 'pct_chg_Metro')
  ) %>% 
  fmt_percent(columns = c(
    'pct_chg_Memphis',
    'pct_chg_County',
    'pct_chg_Metro'
    )) %>% 
  fmt_number(columns = c(
    'estimate_Memphis', 
    'estimate_County',
    'estimate_Metro'),
    decimals = 0) %>% 
  cols_label(
    'estimate_Memphis' = '2020',
    'pct_chg_Memphis' = '2010-2020',
    'estimate_County' = '2020', 
    'pct_chg_County' = '2010-2020',
    'estimate_Metro' = '2020', 
    'pct_chg_Metro' = '2010-2020',
    'variable' = ' '
  ) %>% 
  tab_footnote(
    footnote = "Population is the Total Population in Occupied Housing, which excludes people living in group quarters."
  ) %>% 
  tab_footnote(
    footnote = "Source: 5-Year ACS 2005-2010 & 2015-2020"
  ) %>% 
  tab_header(
    title = "Population and Households in Memphis Area",
    subtitle = "Exclusive geographies"
  )
```

```{r layout='l-page'}
hsgtblIn %>% 
  pivot_wider(names_from = NAME, 
              values_from = c(estimate, pct_chg)) %>% 
  gt() %>% 
  tab_spanner(
    label = "Memphis",
    columns = c(estimate_Memphis, pct_chg_Memphis)
  ) %>% 
  tab_spanner(
    label = "Shelby County",
    columns = c('estimate_County', 'pct_chg_County')
  ) %>% 
  tab_spanner(
    label = "Memphis Metro",
    columns = c('estimate_Metro', 'pct_chg_Metro')
  ) %>% 
  fmt_percent(columns = c(
    'pct_chg_Memphis',
    'pct_chg_County',
    'pct_chg_Metro'
    )) %>% 
  fmt_number(columns = c(
    'estimate_Memphis', 
    'estimate_County',
    'estimate_Metro'),
    decimals = 0) %>% 
  cols_label(
    'estimate_Memphis' = '2020',
    'pct_chg_Memphis' = '2010-2020',
    'estimate_County' = '2020', 
    'pct_chg_County' = '2010-2020',
    'estimate_Metro' = '2020', 
    'pct_chg_Metro' = '2010-2020',
    'variable' = ' '
  ) %>% 
  tab_footnote(
    footnote = "Source: 5-Year ACS 2005-2010 & 2015-2020"
  ) %>% 
  tab_header(
    title = "Housing Units in Memphis Area",
    subtitle = "Inclusive geographies"
  )
```

```{r layout='l-page'}
hsgtblEx %>% 
  pivot_wider(names_from = NAME, 
              values_from = c(estimate, pct_chg)) %>% 
  gt() %>% 
  tab_spanner(
    label = "Memphis",
    columns = c(estimate_Memphis, pct_chg_Memphis)
  ) %>% 
  tab_spanner(
    label = "Shelby County",
    columns = c('estimate_County', 'pct_chg_County')
  ) %>% 
  tab_spanner(
    label = "Memphis Metro",
    columns = c('estimate_Metro', 'pct_chg_Metro')
  ) %>% 
  fmt_percent(columns = c(
    'pct_chg_Memphis',
    'pct_chg_County',
    'pct_chg_Metro'
    )) %>% 
  fmt_number(columns = c(
    'estimate_Memphis', 
    'estimate_County',
    'estimate_Metro'),
    decimals = 0) %>% 
  cols_label(
    'estimate_Memphis' = '2020',
    'pct_chg_Memphis' = '2010-2020',
    'estimate_County' = '2020', 
    'pct_chg_County' = '2010-2020',
    'estimate_Metro' = '2020', 
    'pct_chg_Metro' = '2010-2020',
    'variable' = ' '
  ) %>% 
  tab_footnote(
    footnote = "Source: 5-Year ACS 2005-2010 & 2015-2020"
  ) %>% 
  tab_header(
    title = "Housing Units in Memphis Area",
    subtitle = "Exclusive geographies"
  )
```
