---
title: "About"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello 👋 My name is Sarah Johnson. I recently graduated from the University of Memphis where I received my master's in urban planning. I am currently seeking a career in the Memphis area related to housing research.

You can contact me at [sarahviamemphis\@gmail.com](mailto:sarahviamemphis@gmail.com)

## <i class="fas fa-graduation-cap"></i> Education

**MA, City and Regional Planning** (August 2021)\
University of Memphis

**BBA, Business Economics** (August 2015)\
University of Memphis\
*Cum Laude*

## <i class="fas fa-briefcase"></i> Experience

**Shelby County Department of Housing** (August 2018-April 2019)\
Graduate Assistant

**University of Memphis** (August 2019-April 2020)\
Graduate Assistant

**International Paper** (July 2017-January 2019)\
Training Administrator

## <i class="fas fa-wrench"></i> Skills

-   ArcGIS (proficient)
-   R, RStudio (proficient)
-   Git, Github (beginner)

## <i class="far fa-lightbulb"></i> Interests

-   Housing quality
-   Housing affordability
