---
title: "Memphis Data"
output:
    flexdashboard::flex_dashboard
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(scales)
library(DT)
```

# Memphis {data-orientation=rows}

```{r message=FALSE, warning=FALSE}
acs <- read_csv("../_data/acs.csv") %>% 
  select(-dataset)
acss <- read_csv("../_data/acs_sum.csv")
v19 <- read_csv("../_data/v19acs1.csv")
v74 <- read_csv("../_data/vB25074.csv")
yr <- read_csv("../_data/year.csv")
```

```{r}
acs3 <- acss %>% 
  select(-c(summary_est, summary_moe)) %>% 
  rbind(acs)
```

```{r}
vYoY2 <- c(
  "B25119_001" = "Median Income",
  "B25119_002" = "Median Owner Income",
  "B25119_003" = "Median Renter Income",
  "B25058_001" = "Median Contract Rent",
  "B25064_001" = "Median Gross Rent",
  "B25071_001" = "Median Rent Burden"
)
```

```{r}
yoy2 <- acs3 %>% 
  filter(str_detect(variable, "B25(058|064|071|119)")) %>% 
  arrange(variable, year) %>% 
  group_by(variable) %>% 
  mutate(prev = lag(estimate), .after = estimate,
         diff = estimate - prev,
         diff = replace_na(diff, 0),
         variable = recode_factor(variable, !!!vYoY2)) 
```

## Row

### Income

```{r}
ggyoy2 <- yoy2 %>% 
  filter(str_detect(variable, "Income")) %>% 
  ggplot(aes(x = year, y = diff, color = variable)) +
  geom_line() +
  scale_x_continuous(breaks = unique(yoy2$year)) +
  theme_light()

ggplotly(ggyoy2)
```

## Row

### Rent

```{r}
ggyoy3 <- yoy2 %>% 
  filter(str_detect(variable, "Rent\\b")) %>% 
  ggplot(aes(x = year, y = diff, color = variable)) +
  geom_line() +
  scale_x_continuous(breaks = unique(yoy2$year)) +
  theme_light()

ggplotly(ggyoy3)
```

## Row {.sidebar}

```{r}
yoy2 %>% 
  summarise(sum = sum(diff)) %>% 
  datatable()
```


# Variables
## Col1

```{r}
vYoY <- c(
  "B25002_001" = "Housing Units",
  "B25002_002" = "Occupied Units",
  "B25002_003" = "Vacant Units",
  "B25008_001" = "Population",
  "B25008_002" = "Owners",
  "B25008_003" = "Renters"
)
```


```{r}
yoy <- acss %>% 
  filter(str_detect(variable, "B2500(2|8)")) %>% 
  arrange(variable, year) %>% 
  group_by(variable) %>% 
  mutate(prev = lag(estimate), .after = estimate,
         diff = estimate - prev,
         diff = replace_na(diff, 0),
         variable = recode_factor(variable, !!!vYoY)) 
```

### Variables

```{r}
ggyoy <- yoy %>% 
  ggplot(aes(x = year, y = diff, color = variable)) +
  geom_line() +
  scale_x_continuous(breaks = unique(yoy$year)) +
  theme_light()

ggplotly(ggyoy)
```

## dfs {data-width="220"}

### Change 

```{r}
yoy %>% 
  summarise(sum = sum(diff))
```


# Small
## Col2

### B25008_001: Population in Occupied Housing Units

```{r}
pop <- acss %>% 
  filter(variable == "B25008_001")

ggpop <- pop %>% 
  ggplot(aes(x = year, y = estimate, group = 1)) +
  geom_ribbon(aes(ymax = estimate + moe, ymin = estimate - moe),
              fill = "navy",
              alpha = 0.4) +
  geom_line(color = "navy") +
  scale_y_continuous(labels = label_number(scale = .001, suffix = "K"))+
  scale_x_continuous(breaks = unique(pop$year)) +
  labs(title = "Population in Memphis, 2005-2019",
       y = "ACS estimate",
       x = "Year",
       caption = "Shaded area represents margin of error around the ACS estimate") +
  theme_light()

ggplotly(ggpop)
```
### B25002_002: Occupied

```{r}
hh <- acss %>% 
  filter(str_detect(variable, "B25002_00(1|2)")) %>% 
  mutate(variable = recode_factor(variable,
                                  "B25002_001" = "Housing Units",
                                  "B25002_002" = "Occupied Units"))

ggpop <- hh %>% 
  ggplot(aes(x = year, y = estimate, color = variable, group = 1)) +
  geom_ribbon(aes(ymax = estimate + moe, ymin = estimate - moe),
              fill = "navy",
              alpha = 0.4) +
  geom_line() +
  scale_y_continuous(labels = label_number(scale = .001, suffix = "K"))+
  scale_x_continuous(breaks = unique(hh$year)) +
  labs(title = "Households in Memphis, 2005-2019",
       y = "ACS estimate",
       x = "Year",
       caption = "Shaded area represents margin of error around the ACS estimate") +
  theme_light()

ggplotly(ggpop)
```


## Col 2

### Vacancy Rate

```{r}
hsg <- acss %>% 
  filter(str_detect(variable, "B25002_003")) %>% 
  mutate(pct = (estimate / summary_est)*100)
```

```{r}
ggocc <- hsg %>% 
  ggplot(aes(x = year, y = pct)) +
  geom_line() +
  scale_x_continuous(breaks = unique(hsg$year)) +
  labs(title = "Vacancy Rate in Memphis, 2005-2019",
       y = "ACS estimate",
       x = "Year",
       caption = "Shaded area represents margin of error around the ACS estimate") +
  theme_light()

ggplotly(ggocc)
```

### B25077_001: Median Home Value

```{r}
gghsg <- acs %>%
  filter(str_detect(variable, "B25077")) %>% 
  ggplot(aes(x = year, y = estimate, group = 1)) +
  geom_ribbon(aes(ymax = estimate + moe, ymin = estimate - moe),
              fill = "navy",
              alpha = 0.4) +
  geom_line(color = "navy") +
  scale_y_continuous(labels = label_dollar(scale = .001, suffix = "K"))+
  scale_x_continuous(breaks = unique(acs$year)) +
  labs(title = "Median Home Value in Memphis, 2005-2019",
       y = "ACS estimate",
       x = "",
       color = "Dataset") +
  theme_light()

ggplotly(gghsg)
```

# Cost Burden

```{r}
cb <- acss %>% 
  filter(str_starts(variable, "B25070"))
```

```{r}
vCB <- c(
  "B25070_002" = "Affordable Rent",
  "B25070_003" = "Affordable Rent",
  "B25070_004" = "Affordable Rent",
  "B25070_005" = "Affordable Rent",
  "B25070_006" = "Affordable Rent",
  "B25070_007" = "Rent Burdened",
  "B25070_008" = "Rent Burdened",
  "B25070_009" = "Rent Burdened",
  "B25070_010" = "Extremely Rent Burdened",
  "B25070_011" = "Not Computed"
)
```

```{r}
cb2 <- cb %>% 
  filter(variable != "B25070_001") %>% 
  mutate(variable = recode_factor(variable, !!!vCB)) %>% 
  group_by(year, variable) %>% 
  summarise(estimate = sum(estimate), summary_est = summary_est) %>% 
  ungroup() %>% 
  distinct() %>% 
  mutate(pct = (estimate / summary_est)*100)
```

```{r}
ggcb2 <- cb2 %>%
  ggplot(aes(x = year, y = pct, fill = variable)) +
  geom_col(position = "fill") +
  scale_y_reverse() +
  scale_x_continuous(breaks = unique(cb2$year)) +
  labs(title = "Cost Burden in Memphis, 2005-2019",
       y = "Percent",
       x = "",
       color = "Dataset") +
  theme_light()

ggplotly(ggcb2)
```

# CB Detail

## Col {.tabset}

```{r message=FALSE, warning=FALSE}
grapi <- acss %>%
  filter(str_starts(variable, "B25074")) %>%
  left_join(v74, by = c("year", "variable")) %>%
  separate(label,
           into = c("A", "B", "income", "burden"),
           sep = "!!") %>%
  select(-c(concept, A, B, summary_moe)) %>% 
  mutate(income = str_remove_all(income, ":"))
```

```{r}
vGr <- c(
  "Less than 20.0 percent",
  "20.0 to 24.9 percent",
  "25.0 to 29.9 percent",
  "30.0 to 34.9 percent",
  "35.0 to 39.9 percent",
  "40.0 to 49.9 percent",
  "50.0 percent or more",
  "35.0 percent or more",
  "Not computed"
)

vGr2 <- c(
  "Less than 20.0 percent" = "Affordable",
  "20.0 to 24.9 percent" = "Affordable",
  "25.0 to 29.9 percent" = "Affordable",
  "30.0 to 34.9 percent" = "Burdened",
  "35.0 to 39.9 percent" = "Burdened",
  "40.0 to 49.9 percent" = "Burdened",
  "50.0 percent or more" = "Burdened",
  "35.0 percent or more" = "Burdened",
  "Not computed" = "Not computed"
)

vInc <- c(
  "Less than $10,000" = "Less than $10,000",
  "$10,000 to $19,999" = "$10,000 to $19,999",
  "$20,000 to $34,999" = "$20,000 to $34,999",
  "$35,000 to $49,999" = "$35,000 to $49,999",
  "$50,000 to $74,999" = "$50,000 to $74,999",
  "$75,000 to $99,999" = "$75,000 or more",
  "$100,000 or more" = "$75,000 or more"
)
```

```{r}
graphiD <- grapi %>% 
  filter(!is.na(burden)) %>% 
  group_by(year, income) %>% 
  mutate(group_est = sum(estimate), .before = summary_est,
         income = fct_inorder(income),
         burden = factor(burden, vGr)) %>% 
  ungroup()

graphiD2 <- grapi %>% 
  select(year, income, burden, estimate) %>%
  filter(!is.na(burden)) %>%
  mutate(
    burden = if_else(income != "Less than $10,000" & burden == "Not computed", "Affordable", burden)
  ) %>% 
  group_by(year, income) %>% 
  mutate(income = recode(income, !!!vInc),
         burden = recode_factor(burden, !!!vGr2)) %>% 
  ungroup() %>%
  distinct() %>% 
  group_by(year, income, burden) %>% 
  mutate(estimate = sum(estimate)) %>% 
  ungroup() %>% 
  distinct() %>% 
  mutate(income = fct_inorder(income))
```

### Estimates

```{r}
gggD2 <- graphiD2 %>% 
  ggplot(aes(x = year, y = estimate, fill = burden)) +
  geom_col() +
  facet_wrap(~income) +
  scale_y_continuous(labels = label_number(scale = .001, suffix = "K")) +
  scale_x_continuous(breaks = unique(graphiD2$year)) +
  scale_fill_manual(values = c("yellowgreen", "tomato", "steelblue")) +
  labs(title = "Cost Burden in Memphis, 2005-2019",
       y = "",
       x = "",
       color = "Dataset") +
  theme_light()

ggplotly(gggD2)
```

### Proportions

```{r}
gggD2 <- graphiD2 %>% 
  ggplot(aes(x = year, y = estimate, fill = burden)) +
  geom_col(position = "fill") +
  facet_wrap(~income) +
  scale_y_continuous(labels = label_percent()) +
  scale_x_continuous(breaks = unique(graphiD2$year)) +
  scale_fill_manual(values = c("yellowgreen", "tomato", "steelblue")) +
  labs(title = "Cost Burden in Memphis, 2005-2019",
       y = "",
       x = "",
       color = "Dataset") +
  theme_light()

ggplotly(gggD2)
```