
```{r}
library(tidyverse)
library(tidycensus)
```


```{r message=FALSE, warning=FALSE}
acs <- read_csv("../_data/acs.csv")
acss <- read_csv("../_data/acs_sum.csv")
v19 <- read_csv("../_data/v19acs1.csv")
yr <- read_csv("../_data/year.csv")
yr5 <- read_csv("../_data/year5.csv")

y05 <- 2005:2019
y15 <- c(2015, 2020)
y20 <- 2009:2020

options(tigris_use_cache = TRUE)
```

```{r}
vacs5 <- read_csv("../_data/vacs5.csv")
```


```{r}
vsum <- v19 %>% 
  filter(str_detect(name, "\\d_001"),
         !str_detect(concept, "ALLOCATION"))
```

```{r}
vACS5 <- map_dfr(y20, ~ {
  load_variables(.x, dataset = "acs5")}, .id = "yr")
```

```{r}
vACS5 <- vACS5 %>% 
  mutate(yr = as.numeric(yr)) %>%
  left_join(yr) %>% 
  select(-yr) %>% 
  select(year, everything()) %>% 
  rename(variable = name)
```

```{r}
vACS1 <- vACS1 %>%
  filter(!str_detect(variable, "PR"))
```

```{r}
write_csv(vACS1, "../_data/vacs1.csv")
```

```{r}
v19w <- v19 %>% 
  separate(label, sep = "(\\:)?!!", into = c("v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8"))
```

# Get variable names

```{r}
vACS1 <- read_csv("../_data/vacs1.csv")
```


```{r}
v118 <- vACS1 %>% 
  filter(str_starts(variable, "B25118")) 

write_csv(v118, "../_data/vB25118.csv")
```

```{r}
vDL <-
  acss %>% 
  filter(str_ends(variable, "_001")) %>% 
  select(variable) %>% 
  distinct() %>% 
  left_join(v19, by = c("variable" = "name"))
```


# Summary

```{r}
ACS1 <- map_dfr(y05, ~ {
  get_acs(
    geography = "place",
    survey = "acs1",
    table = "B07013",
    summary_var = "	B07013_001",
    state = "TN",
    year = .x,
    cache_table = TRUE
  )
}, .id = "yr") %>% 
  filter(str_detect(NAME, "Memphis")) %>% 
  mutate(yr = as.numeric(yr))
```

# fixes error w/ summary variable
```{r}
ACS1 <- map_dfr(y05, ~ {
  get_acs(
    geography = "place",
    survey = "acs1",
    table = "B25118",
    state = "TN",
    year = .x,
    cache_table = TRUE
  )
}, .id = "yr") %>% 
  filter(str_detect(NAME, "Memphis")) %>% 
  mutate(yr = as.numeric(yr)) %>% 
  group_by(yr) %>% 
  mutate(summary_est = first(estimate),
         summary_moe = first(moe)) %>% 
  ungroup()
```

```{r}
ACS1 <- ACS1 %>%
  left_join(yr) %>% 
  select(-yr) %>% 
  select(year, everything())
```

```{r}
acss <- rbind(acss, ACS1)
write_csv(acss, "../_data/acs_sum.csv")
```

# ACS5 single variable geometry

```{r}
library(sf)
```

```{r}
ACS2 <- map_dfr(y15, ~ {
  get_acs(
    geography = "tract",
    county = "Shelby",
    survey = "acs5",
    table = "B25002",
    state = "TN",
    year = .x,
    cache_table = TRUE,
    geometry = TRUE
  )
}, .id = "yr")
```

```{r}
ACS2 <- ACS2 %>% 
  left_join(yr5) %>% 
  select(-yr) %>% 
  select(year, everything()) %>% 
  mutate(dataset = "ACS5")
```

```{r}
st_write(ACS2, "../_data/geo/acsg.shp")
```

```{r}
library(tigris)
```

```{r}
shelby_blocks <- blocks(
  state = "TN",
  county = "Shelby",
  year = 2020
)
```

```{r}
st_write(shelby_blocks, "../_data/geo/blocks.shp")
```

```{r}
memphis <- places(state = "TN") %>% 
  filter(NAME == "Memphis")
```

```{r}
memtracts <- mv_shift %>% 
  st_filter(memphis, .predicate = st_within)
```

# Comparison Profiles

```{r}
mv_compare <- get_acs(
  geography = "tract",
  
)
```

```{r}
vcom <- load_variables(2020, dataset = "acs5/cprofile")
```


# Single Variable

```{r}
ACS2 <- map_dfr(y05, ~ {
  get_acs(
    geography = "place",
    survey = "acs1",
    variables = "B25077_001",
    state = "TN",
    year = .x,
    cache_table = TRUE
  )
}, .id = "yr") %>% 
  filter(str_detect(NAME, "Memphis")) %>% 
  mutate(yr = as.numeric(yr))
```

```{r}
ACS2 <- ACS2 %>%
  left_join(yr) %>% 
  select(-yr) %>% 
  select(year, everything()) %>% 
  mutate(dataset = "ACS1")
```

```{r}
acs <- rbind(acs, ACS2)
write_csv(acs, "../_data/acs.csv")
```
